// GENERATED by tools/assemble.mjs from tools/lib/env.mjs -- do not edit.
//
// The filter-list preprocessor environment, shared by the build and the service
// worker. If these drift, a list refetched by "Update all" compiles differently
// from how it was compiled at build time, and filters appear or vanish with no
// error anywhere. See tools/lib/env.mjs for why each token is present.
export const ENV = [
    "ublock",
    "ubol",
    "chromium",
    "mv3",
    "user_stylesheet"
];
