// Assemble the loadable extension: bundle the service worker, copy runtime
// source, build the manifest from the emitted rulesets, and enforce the two
// invariants that otherwise fail silently.
import {
    readFileSync, writeFileSync, mkdirSync, copyFileSync, existsSync, readdirSync, statSync,
} from 'node:fs';
import { resolve } from 'node:path';
import { build } from 'esbuild';
import { ROOT, PARENT, readBackup, describeConfig } from './lib/backup.mjs';
import { ENV } from './lib/env.mjs';
import { SHARD_COUNT, shardOf } from './lib/shardcfg.mjs';

const SRC = resolve(ROOT, 'src');
const DIST = resolve(ROOT, 'extension');
const BUILD = resolve(ROOT, 'build');
const UBO = resolve(PARENT, 'uBlock0.chromium');

/* ---------------------------------------------------------------------- */
/* Invariant 1: the runtime env must match the build env                   */

function syncEnvRuntime() {
    const target = resolve(SRC, 'lib', 'env-runtime.js');
    const generated = `// GENERATED by tools/assemble.mjs from tools/lib/env.mjs -- do not edit.
//
// The filter-list preprocessor environment, shared by the build and the service
// worker. If these drift, a list refetched by "Update all" compiles differently
// from how it was compiled at build time, and filters appear or vanish with no
// error anywhere. See tools/lib/env.mjs for why each token is present.
export const ENV = ${JSON.stringify(ENV, null, 4)};
`;
    const previous = existsSync(target) ? readFileSync(target, 'utf-8') : '';
    writeFileSync(target, generated);
    return previous !== generated;
}

/* ---------------------------------------------------------------------- */
/* Invariant 2: build and runtime must shard hostnames identically         */

async function verifyShardAgreement() {
    const mod = await import(`file://${resolve(SRC, 'lib', 'shard.js')}`);
    if ( mod.SHARD_COUNT !== SHARD_COUNT ) {
        throw new Error(
            `shard count mismatch: src/lib/shard.js has ${mod.SHARD_COUNT}, ` +
            `tools/lib/shardcfg.mjs has ${SHARD_COUNT}`
        );
    }
    // Compare across a broad sample rather than a token few.
    const samples = [];
    for ( let i = 0; i < 20000; i++ ) {
        samples.push(`h${i}.example${i % 97}.co${i % 7}.uk`);
    }
    samples.push('youtube.com', 'www.youtube.com', 'a.b.c.d.example.com', 'xn--80ak6aa92e.com');
    for ( const h of samples ) {
        if ( mod.shardOf(h) !== shardOf(h) ) {
            throw new Error(`shardOf disagreement on "${h}": ` +
                `runtime=${mod.shardOf(h)} build=${shardOf(h)}`);
        }
    }
    return samples.length;
}

/* ---------------------------------------------------------------------- */

// Icons come from the vendored uBO fetch. A local uBlock0.chromium checkout is
// accepted as a fallback, but must not be required: relying on it made CI fail,
// since that folder only exists on the machine this was first built on.
function copyIcons() {
    const outDir = resolve(DIST, 'img');
    mkdirSync(outDir, { recursive: true });
    const wanted = [ 'icon_16.png', 'icon_32.png', 'icon_64.png', 'icon_128.png' ];
    const sources = [ resolve(ROOT, 'vendor/ubo-icons'), resolve(UBO, 'img') ];

    const copied = [];
    for ( const name of wanted ) {
        const from = sources.map(d => resolve(d, name)).find(p => existsSync(p));
        if ( from === undefined ) { continue; }
        copyFileSync(from, resolve(outDir, name));
        copied.push(name);
    }
    if ( copied.length !== wanted.length ) {
        throw new Error(
            `missing icons: ${wanted.filter(w => copied.includes(w) === false).join(', ')}\n` +
            `  looked in: ${sources.join('\n             ')}\n` +
            `  run "npm run vendor" to fetch them`
        );
    }
    return copied;
}

function copyRuntimeFiles() {
    const files = [ 'content.js', 'popup.html', 'popup.js', 'dashboard.html', 'dashboard.js' ];
    for ( const f of files ) {
        copyFileSync(resolve(SRC, f), resolve(DIST, f));
    }
    return files;
}

// Version is <major>.<minor>.<build>, where build simply counts rebuilds.
//
// Chrome requires 1-4 dot-separated integers in 0-65535, so a date cannot be
// embedded readably (20260916 overflows, and 1.26.916.2255 is unreadable). A
// plain counter is what a version number is for: "am I on the latest build?"
// is answered by comparing one small number. The date goes in version_name,
// which is what Chrome actually displays.
const PACKAGE_VERSION = '1.0'; // bump by hand for real releases

function buildVersion(now = new Date()) {
    const p = v => String(v).padStart(2, '0');
    const stamp = `${now.getFullYear()}-${p(now.getMonth() + 1)}-${p(now.getDate())} ` +
                  `${p(now.getHours())}:${p(now.getMinutes())}`;

    // CI must set the version explicitly. The local counter lives in build/,
    // which is not committed, so every CI run would otherwise restart at 1 --
    // and Chrome only auto-updates when the version INCREASES, so a version that
    // never moves silently breaks updates for everyone already installed.
    const explicit = process.env.EXT_VERSION;
    if ( explicit ) {
        if ( /^\d+(\.\d+){0,3}$/.test(explicit) === false ) {
            throw new Error(
                `EXT_VERSION="${explicit}" is not a valid Chrome version ` +
                `(1-4 dot-separated integers, each 0-65535)`
            );
        }
        for ( const part of explicit.split('.') ) {
            if ( Number(part) > 65535 ) {
                throw new Error(`EXT_VERSION part "${part}" exceeds 65535`);
            }
        }
        return { version: explicit, build: explicit.split('.').pop(), stamp };
    }

    const counterPath = resolve(BUILD, 'build-number.txt');
    let n = 0;
    if ( existsSync(counterPath) ) {
        n = parseInt(readFileSync(counterPath, 'utf-8').trim(), 10) || 0;
    }
    n += 1;
    mkdirSync(BUILD, { recursive: true });
    writeFileSync(counterPath, String(n));

    return { version: `${PACKAGE_VERSION}.${n}`, build: n, stamp };
}

function writeManifest() {
    const template = JSON.parse(readFileSync(resolve(SRC, 'manifest.template.json'), 'utf-8'));
    const ruleResources = JSON.parse(readFileSync(resolve(BUILD, 'rule_resources.json'), 'utf-8'));
    template.declarative_net_request.rule_resources = ruleResources;

    // --- version stamp ---
    const plan = JSON.parse(readFileSync(resolve(BUILD, 'emit.plan.json'), 'utf-8'));
    const { version, build, stamp } = buildVersion();
    template.version = version;
    const full = plan.dynamicTokens.length;
    const patched = plan.staticTokens.length;
    const totalRules = plan.totalStaticRules + plan.dynamicRuleCount;
    // No version_name: Chrome renders it in place of the version on the
    // extensions page, and stuffing build stats there reads like debug output.
    // A version should be a version. The build number, date and rule counts are
    // in data/build-info.json and shown in the dashboard, where detail belongs.
    delete template.version_name;

    // The dashboard reads this so the build is identifiable from inside the UI,
    // not just from chrome://extensions.
    writeFileSync(resolve(DIST, 'data', 'build-info.json'), JSON.stringify({
        version,
        build,
        builtAt: new Date().toISOString(),
        builtAtLocal: stamp,
        totalLists: full + patched,
        fullUpdateLists: full,
        patchedLists: patched,
        staticRulesets: ruleResources.length,
        staticRules: plan.totalStaticRules,
        dynamicRules: plan.dynamicRuleCount,
        totalRules,
        patchedTokens: plan.staticTokens,
    }, null, 2));

    // The generic cosmetic stylesheet is injected declaratively -- no lookup and
    // no message round-trip, so it applies before the page paints.
    template.content_scripts[0].css = [ 'data/cosmetic/generic.css' ];

    // Scriptlet bundles and shard files are injected by registerContentScripts,
    // which requires them to be listed as web-accessible.
    template.web_accessible_resources = [ {
        resources: [ 'data/cosmetic/*', 'scriptlets/*' ],
        matches: [ '<all_urls>' ],
    } ];

    writeFileSync(resolve(DIST, 'manifest.json'), JSON.stringify(template, null, 2));
    return { rulesets: ruleResources.length, version, stamp };
}

function dirSize(dir) {
    let total = 0;
    for ( const entry of readdirSync(dir, { withFileTypes: true }) ) {
        const p = resolve(dir, entry.name);
        total += entry.isDirectory() ? dirSize(p) : statSync(p).size;
    }
    return total;
}

async function main() {
    console.log('ASSEMBLE');
    console.log('='.repeat(64));

    const envChanged = syncEnvRuntime();
    console.log(`  env-runtime.js ${envChanged ? 'REGENERATED' : 'up to date'} (${ENV.join(', ')})`);

    const checked = await verifyShardAgreement();
    console.log(`  shard agreement verified across ${checked.toLocaleString()} hostnames`);

    // The service worker imports ubo-core so it can recompile refetched lists;
    // that has to be bundled, since an MV3 worker cannot load bare specifiers.
    const result = await build({
        entryPoints: [ resolve(SRC, 'background.js') ],
        outfile: resolve(DIST, 'background.js'),
        bundle: true,
        format: 'esm',
        target: 'chrome121',
        platform: 'browser',
        legalComments: 'inline',
        logLevel: 'warning',
        metafile: true,
    });
    const swBytes = statSync(resolve(DIST, 'background.js')).size;
    console.log(`  background.js bundled: ${(swBytes / 1024).toFixed(0)} KiB`);
    if ( result.warnings.length !== 0 ) {
        console.log(`  esbuild warnings: ${result.warnings.length}`);
    }

    const icons = copyIcons();
    console.log(`  icons: ${icons.join(', ')}`);

    const runtime = copyRuntimeFiles();
    console.log(`  runtime files: ${runtime.join(', ')}`);

    const { rulesets, version, stamp } = writeManifest();
    console.log(`  manifest.json written with ${rulesets} static rulesets`);

    // A uBO backup lists every site blocking is disabled on, which is a browsing
    // history by another name, plus any personal filters. Those end up verbatim
    // in data/default-config.json, so a build made from one must never be
    // published. Say so loudly rather than leaving it to be noticed.
    const cfg = readBackup();
    const personal = cfg.__personal === true;
    writeFileSync(resolve(DIST, 'data', 'build-provenance.json'), JSON.stringify({
        configSource: cfg.__source,
        personal,
        whitelistEntries: cfg.whitelist.length,
        userFilterLines: cfg.userFilters.split('\n').filter(Boolean).length,
        publishable: personal === false,
    }, null, 2));

    console.log();
    if ( personal ) {
        console.log('  ' + '!'.repeat(64));
        console.log(`  !! PRIVATE BUILD -- ${describeConfig(cfg)}`);
        console.log('  !! extension/data/default-config.json contains your personal');
        console.log('  !! whitelist and filters. Do NOT publish this build or commit');
        console.log('  !! extension/. For a public build, remove config/my-config.json');
        console.log('  !! and any my-ublock-backup_*.txt, or set UBLOCK_MV3_CONFIG to');
        console.log('  !! config/default.json.');
        console.log('  ' + '!'.repeat(64));
    } else {
        console.log(`  publishable build -- ${describeConfig(cfg)}`);
    }

    console.log();
    console.log(`  VERSION ${version}   (built ${stamp})`);
    console.log(`extension/ total size: ${(dirSize(DIST) / 1048576).toFixed(1)} MiB`);
    console.log(`\nLoad it: chrome://extensions -> Developer mode -> Load unpacked -> ${DIST}`);
}

main().catch(err => {
    console.error('\nASSEMBLE FAILED:', err.message);
    if ( err.stack ) { console.error(err.stack); }
    process.exitCode = 1;
});
